Repository team-xquare/v1-service-feed, pull requests merged in 2022-07, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 세팅
  .idea/workspace.xml
  v1-service-feed/.gitignore
  v1-service-feed/build.gradle
  v1-service-feed/feed-domain/build.gradle
  v1-service-feed/feed-infrastructure/build.gradle
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/V1ServiceFeedApplication.java
  v1-service-feed/feed-infrastructure/src/main/resources/application.yml
  v1-service-feed/gradle/wrapper/gradle-wrapper.jar
  v1-service-feed/gradle/wrapper/gradle-wrapper.properties
  v1-service-feed/gradlew
  v1-service-feed/gradlew.bat
  v1-service-feed/settings.gradle
Labels: 프로젝트 설정

#4 🔀 :: (#3) 패키지 구조 설정
  v1-service-feed/.github/CODEOWNERS
  v1-service-feed/.github/ISSUE_TEMPLATE /bug.yml
  v1-service-feed/.github/ISSUE_TEMPLATE /todo.yml
  v1-service-feed/.github/workflows/CI.yml
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/annotation/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/adpter/outside/persistence/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/adpter/outside/persistence/converter/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/application/port/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/application/port/inside/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/application/port/outside/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/application/service/converter/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/comment/application/service/dto/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/feed/.gitkeep
  v1-service-feed/feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/adpter/in/web/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/application/converter/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/application/dto/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/adpter/in/web/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/adpter/in/web/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/.gitkeep
  v1-service-feed/feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/adpter/in/web/.gitkeep
Labels: 프로젝트 설정

#8 🔀 :: (#7) 에러 처리 설정
  feed-domain/src/main/java/com/xquare/v1servicefeed/attachment/error/AttachmentErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/error/CommentErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/error/FeedErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/error/FeedLikeErrorCode.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/error/ErrorResponse.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/error/GlobalErrorCode.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/error/GlobalErrorFilter.java
  feed-infrastructure/src/main/resources/application.yml
Labels: chore, 기능 추가, 리팩토링

#10 🔀 :: (#9) Security 설정
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/config/JpaAuditingConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/role/UserRole.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/AuthenticationFilter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/FilterConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/WebConfig.java
Labels: 기능 추가

#15 🔀 :: (#11) 댓글 생성 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/annotation/Api.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/annotation/Spi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CreateCommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/request/DomainCreateCommnetRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CreateCommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommentQueryFeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/error/FeedErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/exception/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/exception/FeedNotFoundException.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/mapper/AttachmentMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/mapper/CommentMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/request/.gitkeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/request/WebCreateCommentRequest.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/FeedMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
Labels: chore, 기능 추가

#16 🔀 :: (#14) 피드 생성 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/CreateFeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainCreateFeedRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedUuidResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/CreateFeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/CommandFeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/.gitkeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/response/.gitkeep
Labels: 기능 추가

#20 🔀 :: (#18) 댓글 삭제 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/DeleteCommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/DeleteCommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/error/CommentErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/exception/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/exception/CommentNotFoundException.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
Labels: 기능 추가
