Repository team-xquare/v1-service-feed, pull requests merged in 2022-10, with the labels that each got.

#25 🔀 :: (#24) 댓글 수정하기 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/request/CreateCommentDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/request/UpdateCommentDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/request/CreateCommentWebRequest.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/request/UpdateCommentWebRequest.java
Labels: chore, 기능 추가

#30 🔀 :: (#28) 네이밍 통일하기
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
Labels: 리팩토링

#27 🔀 :: (#26) 피드 좋아요 달기 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/request/CreateCommentDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/QueryCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/configuration/spi/SecuritySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/FeedLike.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/FeedLikeApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/dto/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/dto/SaveFeedLikeDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/.gitKeep
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/CommandFeedLikeSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/FeedLikeSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/mapper/FeedLikeMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/web/WebFeedLikeAdapter.java
Labels: chore, 기능 추가, 리팩토링

#31 🔀 :: (#13) 피드 삭제
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/CommandFeedSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
Labels: 기능 추가
