Repository team-xquare/v1-service-feed, pull requests merged in 2022-12, with the labels that each got.

#40 🔀 :: (#35) 피드 목록 조회
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedListElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedListResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/User.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/FeedUserSpi.java
  feed-infrastructure/build.gradle
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/domain/AttachmentEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/domain/AttachmentEntityId.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/domain/mapper/AttachmentMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/domain/repository/AttachmentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/domain/repository/AttachmentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/exception/.gitKeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/web/WebAttachmentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/web/dto/request/.gitkeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/attachment/web/dto/response/.gitkeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/config/QuerydslConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/error/GlobalErrorCode.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/role/UserRole.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/AuthenticationFilter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/role/UserRole.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/vo/FeedListVO.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/FeignClientErrorDecoder.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/FeignConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/UserClient.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/dto/response/UserInfoElement.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/dto/response/UserInfoResponse.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/exception/FeignBadRequestException.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/exception/FeignForbiddenException.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/exception/FeignServerError.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/exception/FeignUnAuthorizedException.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/s3/.gitKeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/user/domain/repository/UserRepositoryAdapter.java
Labels: chore, 기능 추가, 리팩토링

#42 🔀 :: (#41) 피드 목록 조회 API 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedListElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/vo/FeedListVO.java
Labels: chore, 리팩토링

#39 🔀 :: (#34) 댓글 조회하기
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/Comment.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CommentApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/response/CommentDomainElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/QueryCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/CommentUserSpi.java
  feed-infrastructure/build.gradle
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/mapper/CommentMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/vo/CommentListVO.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/WebCommentAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/response/.gitkeep
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/web/dto/response/QueryCommentListResponse.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/entity/BaseUUIDEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/user/domain/repository/UserRepositoryAdapter.java
Labels: chore, 기능 추가, 프로젝트 설정

#44 🔀 :: (#43) 피드&댓글 인가 설정하기
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/QueryCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/error/UserErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/exception/ForbiddenUserException.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/CommentUserSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/FeedUserSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/user/domain/repository/UserRepositoryAdapter.java
Labels: chore

#46 🔀 :: (#45) NPE 방지
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
Labels: 리팩토링

#50 🔀 :: (#47) 피드 수정 시 이미지 넘기기
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/FeedImage.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainUpdateFeedRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/CommandFeedImageSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedImageSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedImageEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedImageEntityId.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/FeedImageMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepsitoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebUpdateFeedRequest.java
Labels: chore, 기능 추가

#52 🔀 :: (#51) 피드 목록 조회 api 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedListElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/FeedImageSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedImageSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/QueryFeedLikeSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
Labels: chore

#56 🔀 :: (#55) 피드 이미지 생성 & 삭제
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedImageApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainCreateFeedImageRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedImageApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedImageAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedImageRequest.java
  feed-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#58 🔀 :: (#57) Security Config 변경
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
Labels: 프로젝트 설정

#59 🔀 :: (#54) 피드 이미지 업데이트 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedImageApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/CreateFeedImageRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/UpdateFeedImageRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedImageApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedImageSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/FeedImageMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedImageAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebUpdateFeedImageRequest.java
Labels: 기능 추가, 리팩토링

#60 🔀 :: (#53) 카테고리 보여주기 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Category.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainCreateFeedRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedCategoryResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/error/CategoryErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/exception/CategoryNotFoundException.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/CategorySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryCategorySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/CategoryEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/CategoryMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/FeedMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/CategoryRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/CategoryRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
Labels: 기능 추가

#62 🔀 :: (#61) CD 설정
  .github/workflows/prod.yml
  .github/workflows/stag.yml
  Dockerfile
Labels: 기능 추가
