Repository team-xquare/v1-service-feed, pull requests merged in 2023-01, with the labels that each got.

#65 🔀 :: (#64) 카테고리 전체 조회 수정 & 카테고리별 피드 전체 조회 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedCategoryElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedCategoryListResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedListResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
Labels: chore

#63 🔀 ::(#48) 피드 생성 api 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/configuration/spi/SecuritySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/CategoryEnum.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/FeedApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainCreateFeedRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedList.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/SaveFeedResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryCategorySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedImageSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/QueryFeedSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/QueryFeedLikeSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/error/UserErrorCode.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/exception/InvalidRoleException.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/role/UserAuthority.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/role/UserRole.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/AuthenticationFilter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/role/UserRole.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/mapper/FeedMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/CategoryRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
Labels: chore

#67 🔀 :: (#66) Enum 파싱 에러 해결
  feed-domain/src/main/java/com/xquare/v1servicefeed/configuration/spi/SecuritySpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/AuthenticationFilter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/CategoryEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
Labels: chore, 리팩토링, 버그

#69 🔀 :: (#68) 피드 생성 에러 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/spi/CommandFeedSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/entity/BaseUUIDEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
Labels: 버그

#73 🔀 :: (#72) 피드 수정하기 API에서 불필요한 request 삭제
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainUpdateFeedRequest.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebUpdateFeedRequest.java
Labels: chore, 버그

#75 🔀 :: (#74) CommentMapper에서 UserId를 추가하지 않아 생기는 문제 해결
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/mapper/CommentMapper.java
Labels: chore, 버그

#71 🔀 :: (#70) 피드 전체 불러오기 API 에러 해결
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedList.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/vo/FeedListVO.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/UserClient.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/dto/response/UserInfoResponse.java
  feed-infrastructure/src/main/resources/application.yml
Labels: 버그

#77 🔀 :: (#76) 댓글 관련 API 에러 해결
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
Labels: chore, 버그

#80 🔀 :: (#79) 피드 좋아요 엔티티 네이밍 문제
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/FeedLikeEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/mapper/FeedLikeMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
Labels: chore

#81 🔀 :: (#78) 피드 좋아요 취소시 FeedId 이용하기
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/FeedLikeApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/dto/SaveFeedLikeDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/QueryFeedLikeSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityConfig.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/web/WebFeedLikeAdapter.java
Labels: 버그
