Repository team-xquare/v1-service-feed, pull requests merged in 2023-08, with the labels that each got.

#108 🔀 :: (#220) 게시글, 댓글 soft delete 추가
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/Comment.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/spi/CommandCommentSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
Labels: 리팩토링

#112 🔀 :: (#111) Soft Delete 오류 수정
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/resources/application.yml
Labels: 리팩토링, 버그

#113 🔀 :: (#227) response에 categoryId 추가
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedWeakElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
Labels: chore
