Repository team-xquare/v1-service-feed, pull requests merged in 2023-03, with the labels that each got.

#89 🔀 :: (#88) Feed 삭제 에러 해결
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/spi/CommandFeedLikeSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
Labels: 버그

#91 🔀 :: (#90) feed 신고 API
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/Report.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/api/ReportApi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/api/dto/CreateReportDomainRequest.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/api/impl/ReportApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/spi/CommandReportSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/report/spi/ReportSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/WebFeedAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/domain/ReportEntity.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/domain/ReportRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/domain/mapper/ReportMapper.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/domain/mapper/ReportMapperImpl.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/domain/repository/ReportRepository.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/report/web/dto/request/CreateReportWebRequest.java
Labels: 기능 추가

#93 🔀 :: (#92) 피드 카테고리 조회 시 사용자 권한 추가
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/AuthorityElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/AuthorityListByTypeResponse.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/response/FeedCategoryElement.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/FeedAuthoritySpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/AuthorityClient.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/user/domain/repository/AuthorityRepositoryAdapter.java
Labels: chore, 기능 추가

#95 🔀 :: (#94) Feed 500에러 해결
  feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/CommentUserSpi.java
  feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/FeedUserSpi.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedRepositoryAdapter.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feign/client/UserClient.java
  feed-infrastructure/src/main/java/com/xquare/v1servicefeed/user/domain/repository/UserRepositoryAdapter.java
Labels: chore, 버그
